version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - MONGODB_URI=${MONGO_URL}
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
