name: Docker Image CI

on:
  push:
    branches: 
      - publish

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build server Docker image
        working-directory: ./server
        run: docker build -t cvetankapasinechka/cupinja:project .

      - name: Build client Docker image
        working-directory: ./client
        run: docker build -t cvetankapasinechka/client:project .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push server Docker image to Docker Hub
        run: docker push cvetankapasinechka/cupinja:project

      - name: Push client Docker image to Docker Hub
        run: docker push cvetankapasinechka/client:project
